name: deep-py312
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - lightgbm
  - matplotlib
  - notebook
  - numpy==1.26.4
  - openpyxl
  - pandas
  - pathlib
  - pillow
  - pyarrow
  - rich
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - xgboost
  - xlrd
  - gradio
  - graphviz
  - numpy-base=1.26.4
